name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      env: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Change to your AWS region

    - name: Login to Amazon ECR
      run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

    - name: Pull Docker image
      run: sudo docker pull ${{ AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com:myapp-latest
    - name: Delete Old docker container
      run: sudo docker rm -f cicd-pipeline-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name cicd-pipeline-container ${{ AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com:myapp-latest
